<?php

namespace App\Exports\Qiyas;

use App\Models\Standard;
use Maatwebsite\Excel\Concerns\WithMultipleSheets;

/**
 * The single official Qiyas requirements import/export template. The
 * importer only ever trusts a file generated by this class — see
 * docs/qiyas-xlsx-import.md.
 */
class QiyasRequirementsTemplateExport implements WithMultipleSheets
{
    public function __construct(
        private readonly string $programCode,
        private readonly ?int $programId = null,
        private readonly ?int $cycleId = null,
    ) {}

    public function sheets(): array
    {
        $perspectives = [];
        $axes = [];
        if ($this->programId) {
            $perspectives = Standard::where('compliance_program_id', $this->programId)
                ->whereNotNull('perspective')->distinct()->pluck('perspective')->values()->all();
            $axes = Standard::where('compliance_program_id', $this->programId)
                ->whereNotNull('axis')->distinct()->pluck('axis')->values()->all();
        }

        return [
            new RequirementsSheet,
            new InstructionsSheet,
            new AllowedValuesSheet($perspectives, $axes),
            new MetadataSheet($this->programCode, $this->cycleId),
        ];
    }
}
