<?php

namespace App\Exports\Qiyas;

use App\Models\ComplianceProgram;
use App\Models\Standard;
use App\Services\ProgramConfigurationService;
use Maatwebsite\Excel\Concerns\WithMultipleSheets;

/**
 * The single official Qiyas requirements import/export template. The
 * importer only ever trusts a file generated by this class — see
 * docs/qiyas-xlsx-import.md.
 *
 * As of Phase 4, the Requirements sheet's column list is resolved from the
 * program's 'import' configuration (see docs/import-export-engine.md)
 * rather than being fixed to Qiyas's column set in code — a future
 * program's importer reuses this exact export/validation pipeline with its
 * own configured columns, not a copy of this class.
 */
class QiyasRequirementsTemplateExport implements WithMultipleSheets
{
    public function __construct(
        private readonly string $programCode,
        private readonly ?int $programId = null,
        private readonly ?int $cycleId = null,
    ) {}

    public function sheets(): array
    {
        $perspectives = [];
        $axes = [];
        if ($this->programId) {
            $perspectives = Standard::where('compliance_program_id', $this->programId)
                ->whereNotNull('perspective')->distinct()->pluck('perspective')->values()->all();
            $axes = Standard::where('compliance_program_id', $this->programId)
                ->whereNotNull('axis')->distinct()->pluck('axis')->values()->all();
        }

        $columns = $this->resolveColumns();

        return [
            new RequirementsSheet($columns),
            new InstructionsSheet,
            new AllowedValuesSheet($perspectives, $axes),
            new MetadataSheet($this->programCode, $this->cycleId, $columns),
        ];
    }

    /** Column keys from the program's 'import' configuration, falling back to RequirementsSheet::COLUMNS if none is set yet. */
    private function resolveColumns(): ?array
    {
        if (! $this->programId) {
            return null;
        }

        $program = ComplianceProgram::find($this->programId);
        if (! $program) {
            return null;
        }

        $config = app(ProgramConfigurationService::class)->get($program, 'import', []);
        $columns = collect($config['columns'] ?? [])->pluck('key')->filter()->values()->all();

        return $columns ?: null;
    }
}
